ProxymanApp/atlantis

Atlantis.xcodeproj/Atlantis_Info.plist
Atlantis.xcodeproj/project.pbxproj
Sources/Atlantis.swift
Sources/Configuration.swift
Sources/DataCompression.swift
Sources/Transporter.swift

- Add DataCompression
- Compress the data before sending

Compress gzip before sending

---

Sources/Atlantis.swift
Sources/NetworkInjector+URLSession.swift
Sources/NetworkInjector.swift

Fix could not cast to URLSessionDataTask

---

Atlantis.xcodeproj/project.pbxproj
Sources/Atlantis+Manual.swift
Sources/Atlantis.swift
Sources/Packages.swift
Sources/Runtime.swift

- Add to Atlantis from URLRequest and URLResponse
- Add to Atlantis from Request and Response models
- Add from GRPC Message
#36

Able to add Request / Response / GRPC message to Atlantis

---

Sources/NetworkInjector.swift
Sources/Packages.swift

- Support Catalyst 
- Fix crash when could not found URLSession from Catalyst app

Support Catalyst

---

Atlantis-Example/Atlantis-Example/ViewController.swift
Atlantis-Example/Podfile.lock
Sources/Atlantis.swift

- Use `queue.sync` to prevent the URLRequest.httpBody is released

[BUG] Missing Request's Body in some scenario

---

Package.swift
Sources/Packages.swift

quick fix to support tvOS

---

Sources/NetworkInjector+URLSession.swift
Sources/Packages.swift

- Support local download task
- Fix the body data is called twice
- #47

Fix crash on DownloadTask

---

Sources/Atlantis.swift
Sources/NetworkInjector+URLSession.swift
Sources/NetworkInjector.swift
Sources/Packages.swift

- Perform Method Swizzling on URLSessionUploadTask

Support Atlantis for Upload Tasks

---

Sources/Atlantis.swift
Sources/Packages.swift

- Add a flag to enable/disable the Transport Layer (e.g. Bonjour Service)
- Add Delegate to notify the traffic
- Public some classes

Better interface for Atlantis

---

Objc/AtlantisHelper.m
Sources/Atlantis.swift
Sources/NetworkInjector+URLSession.swift
Sources/NetworkInjector.swift
Sources/Packages.swift
atlantis-proxyman.podspec

- Add tvOS 13
- Update Podspec file to match with SMP

Fix tvOS issue

---

.github/workflows/main.yml

Add a basic Github Actions workflow

---

Objc/AtlantisHelper.m
Package.swift
Sources/Atlantis.swift
Sources/NetworkInjector+URLSession.swift
Sources/NetworkInjector.swift
Sources/Packages.swift
Sources/Transporter.swift
atlantis-proxyman.podspec

- Use NWConnection instead of URLSessionStreamTask
- Bump to iOS 13, tvOS 13, macOS 10.15 as a minimum OS
- Maintain multiple connection to Proxyman app
#72

Support multiple connection to Proxyman apps

---

README.md

Import Atlantis as a module in Objective-C

---

.swiftpm/xcode/xcshareddata/xcschemes/Atlantis.xcscheme
.vscode/settings.json
Example/Atlantis-Example-App/Atlantis-Example-App.xcodeproj/project.pbxproj
Example/Atlantis-Example-App/Atlantis-Example-App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Example/Atlantis-Example-App/Atlantis-Example-App/AppDelegate.swift
Sources/Atlantis.swift
Sources/NetworkInjector+URLSession.swift

- Could not swizzle the `URLSession-didReceiveResponse` on the iOS 16
- Better console log for future error

Fix issue on iOS 16 beta

---

Sources/Transporter.swift

- Prevent connecting to a single host multiple times

Fixed: Atlantis connects to the same Host multiple times

---

Sources/Atlantis.swift
Sources/NetworkInjector.swift
atlantis-proxyman.podspec

- Option to opt-out the Method Swizzling on WS/WSS Connection
- Fixed: https://github.com/ProxymanApp/atlantis/issues/134

Option to opt-out the Method Swizzling on WS/WSS Connection

---

Package.swift
Sources/PrivacyInfo.xcprivacy

- Add Privacy Manifest: https://developer.apple.com/support/third-party-SDK-requirements/

Add Privacy Manifest

---

Example/AtlantisSwiftUIApp/AtlantisSwiftUIApp.xcodeproj/xcshareddata/xcschemes/AtlantisSwiftUIApp.xcscheme
Example/AtlantisSwiftUIApp/AtlantisSwiftUIApp/AtlantisSwiftUIAppApp.swift
Sources/Atlantis.swift
Sources/Transporter.swift
atlantis-proxyman.podspec

https://github.com/ProxymanApp/atlantis/issues/165
- iOS Simulator: Make a direct connection to Proxyman app on the current Mac device => Fix the macOS 15.4 issue ✅ 
- iOS Devices: Use Bonjour Service as usual
- Upgrade to NWBrowser instead of deprecated NetService

New APIs for macOS 15.4 issue

---

Example/AtlantisSwiftUIApp/AtlantisSwiftUIApp/ContentView.swift
Sources/NetworkInjector+URLSession.swift

- Fixed Crashed from uploadTaskWithRequest:fromData in NewRelic Lib

Fixed Crashed from uploadTaskWithRequest:fromData in NewRelic Lib

---

Atlantis.xcodeproj/project.pbxproj
Sources/Atlantis.swift
atlantis-proxyman.podspec

- Fix v1.29.1 that Atlantis can't be build
- Bump 1.29.2

Fix can't build the project. Bump 1.29.2
