ProxymanApp/atlantis

- Atlantis.xcodeproj/AtlantisTests_Info.plist
- Atlantis.xcodeproj/Atlantis_Info.plist
- Atlantis.xcodeproj/project.pbxproj
Hey, 
Thank you so so much for Atlantis! I've been a big fan of Proxyman and I have been using since the beginning. I always wished for an easier way to capture traffic from test devices. I also often forgot to revert the proxy settings on the device and then wonder why it isn't connected anymore 🙄
----
Anyway, I tried to publish an app to TestFlight but the validation doesn't pass. The framework was integrated by Carthage.
```
ERROR ITMS-90056: "This bundle Payload/Flighty Int.app/Frameworks/Atlantis.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"
```
The framework bundle needs to include a value …
> Fix CFBundleVersion in framework bundle

- Sources/Atlantis.swift
- Sources/Configuration.swift
- Sources/Transporter.swift
This PR allows end-users to point out what the Proxyman app that Atlantis will connect to. It's useful if we have multiple Proxyman apps in the same network (e.g. in the company).
- `Atlantis.start()` will connect to all available Proxyman app
- `Atlantis.start(hostName: "mymachine.local.")` will connect to particular machine
> [Feature] Able to connect to particular Proxyman app in company network

- Atlantis.xcodeproj/project.pbxproj
- Package.swift
- atlantis-proxyman.podspec
Since NSNetService and URLSessionStreamTask have already supported from iOS 11+. We should support iOS 11 rather than iOS 12+
Ticket #30 
- Set minimum iOS 11
> Support iOS 11

- Sources/Atlantis.swift
I have an app that uses Chromecast which already has two bonjour services. It took a while of debugging to figure out why Atlantis was giving an error on startup.
I changed from selecting the first bonjour service to the first one matching
> fix bonjour services check

- README.md
- Sources/Atlantis.swift
I wanted to use Atlantis in my Objective-C based project. This change allows Atlantis to be used in Objective-C based projects and demonstrates how to use it with the Swift bridging header.
> Add Objective-C interop

- Sources/Packages.swift
- Sources/Transporter.swift
For some reason, URLStreamTask doesn't send a big file due to overflow? We should skip sending these big files as a temporary solution.
#57
> Add Maximum Package size

- Sources/Atlantis.swift
- Sources/NetworkInjector.swift
We were seeing warnings on these two lines in our xcodebuild output using Xcode 12.5
> using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead
> Fix warnings for depredated use of class for protocol inheritance

- Sources/Transporter.swift
- Set a limit for a pending list (30 items)
- Flush all item if there is a memory warning notification (iOS Only)
- Close #74
> Reduce RAM Consumption

- Package.swift
My understanding is that these exclude specs are not needed. They are outside of the specified `path` so were never considered for inclusion.
Here is a screenshot of the warnings we are getting using Xcode 13 beta 2.
> Fix "Invalid Exclude" warnings

- README.md
- Sources/Atlantis.swift
- Add `isRunningOniOSPlayground` to bypass the Safety check for the Bonjour Service
- Able to integrate Atlantis to Swift Playground (iOS and macOS)
> Atlantis with Swift Playground

- README.md
- Sources/Atlantis+Manual.swift
- Sources/Atlantis.swift
- Sources/Packages.swift
With these additions it’s the first way to make better use of Displaying WebSockets for Streaming Requests in general for gRPC Requests.
I did some breaking changes to determine the usage of unary calls and streaming calls to be better seperated.
In the Readme it’s even provided how to write a proper interecptor for working with that.
> Better GRPC support

- README.md
this PR fixing missing code when I copy example code to my project to capture grpc.
I'm thinking removing duplicated/unnecessary code is easily than search and add missing module/code.
> fix: add missing code for grpc capture example code in README

- README.md
- Sources/Atlantis+Manual.swift
Issue # https://github.com/ProxymanApp/atlantis/issues/106
Starting from  https://github.com/ProxymanApp/atlantis/pull/94/files
there is a typo `startetAt` which should `startedAt`
> Fix StartedAt Typo

- README.md
We had people report that they were seeing the Atlantis/Bonjour dialog on production.
Happy to discuss a better way to surface this information (how to prevent this from happening), or to instruct developers to be careful about this.
> Update README.md : Setup/Run Atlantis only on DEBUG

- Sources/NetworkInjector+URLSession.swift
- Fix Atlantis could not work on tvOS 15.4
> Fix tvOS 15.4

- Sources/Runtime.swift
Should free the return value of `class_copyMethodList `
> fix memory leak of `class_copyMethodList`

- Sources/Atlantis.swift
- Sources/AtlantisHelper.swift
- Remove Websocket `assertionFailure` to prevent crashing
> Remove assert

- Sources/NetworkInjector+URLSession.swift
Per https://developer.apple.com/documentation/foundation/urlsession/1411518-uploadtask, body data parameter may be null.
This PR should fix https://github.com/ProxymanApp/atlantis/issues/132.
> Fix crash when intercepting URLSessionUploadTask.

- Sources/Packages.swift
This PR adds support for visionOS in Atlantis. As of now, Atlantis builds fail for visionOS.
> feat: Add visionOS support

- Sources/Packages.swift
When `AVAggregateAssetDownloadTask` is started, Atlantis crashes running app, because it checks `currentRequest` property which is not supported. 
Thrown exception explicitly states:
> AVAggregateAssetDownloadTask does not support currentRequest property
As skipping is definitely better option to crashing, this PR skips tracking this type of tasks.
> Fix AVAggregateAssetDownloadTask crash

- Sources/Atlantis.swift
I have an idea to prevent the duplicate records issue when using with URLProtocol. The issue has been mentioned in: https://github.com/ProxymanApp/atlantis/issues/154
> feat: Support to set ignored URLProtocol classes

- Sources/Atlantis.swift
In the previous pull request  https://github.com/ProxymanApp/atlantis/pull/155, I added a fix for the duplicate request issue caused by the app using URLProtocol, but there was one issue: I checked all the requests with the protocol that needed to be ignored, but I forgot that only those URLSessions with URLProtocol are processed, resulting in some URLDataTasks using other URLSessions being overlooked
> hotfix: Fix missing requests when ignore urlprotocol

- Sources/Atlantis.swift
- Sources/Packages.swift
- Sources/URLSessionTask+CurrentRequest.swift
This was already fixed in https://github.com/ProxymanApp/atlantis/pull/151 but unfortunately reintroduced by another call to `.currentRequest` in https://github.com/ProxymanApp/atlantis/commit/b9542919ae59dbecff5374c52c40cb62d2f57164
This PR adds a new extension to move the access check to a shared location
> Make sure all accesses to `URLSessionTask.currentRequest` are crash safe
